# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37dbcd8ff4e80c67c69a193aaf318c1e8d954bcf8de73981504ef66ab49ac08b94c62c82fac1982f44d12811596065ff02d00b77ccf0e835572a1e13120cf44

test:
  secret_key_base: 225c4f738cb5039d877c2c448e463358ad5b3ac6f2e2811981888cc73f528f08430da94a00d52ea4400ec03ba74729ef3b09a300f6afcdb04e8ff2978212dc79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
